baseURL = 'https://nicomeuwly.github.io/labveiltec-portfolio/'
languageCode = 'fr-ch'
title = 'Nicolas Meuwly'
theme = "paper"
paginate = 3

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  github = 'nicomeuwly'                     # github.com/YOUR_GITHUB_ID
  linkedin = 'nicolas-meuwly'             # linkedin.com/in/YOUR_LINKEDIN_ID

  # home page profile
  avatar = 'https://media.licdn.com/dms/image/D4E03AQEBkxeD2YXZmA/profile-displayphoto-shrink_800_800/0/1696271633679?e=1711584000&v=beta&t=F0fy8HxxC_xL7PcQHS772M7TpwxFe3DR2y9YwGw1KYY'                 # gravatar email or image url
  name = 'Nicolas Meuwly'
  bio = 'Bienvenue sur mon portfolio dédié à ma veille technologique !'


  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = true                               # enable KaTeX math typesetting globally
  graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)

  [menu]

  [[menu.main]]
    identifier = "about"
    name = "A propos"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/post/"
    weight = 10